version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8181:80
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./webapp:/webapp
      - ./site.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - db
    links:
      - db:db
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
      - ./webapp:/webapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
